### ISSUE TITLE
naming bug

### ISSUE THREAD

**Issue by BeccaHyland** [launchdarkly/hello-java#10]
Hi, this repo is linked in the [app Quickstart docs](https://app.launchdarkly.com/default/production/quickstart), so noting here a minor naming mismatch between the tutorial project's class file `App.java` (as downloaded in step 2a: `mvn archetype:generate -DgroupId=com.launchdarkly.tutorial -DartifactId=hello-java`) compared to the class `Hello.java` referenced in the Maven Assembly Plugin code in documentation step 2c, line: `<mainClass>Hello</mainClass>` and step 2e, line: `public class Hello {`

Was not a big deal to resolve the naming, only detracted a little from the "It Just Works!" feeling when setting up LaunchDarkly for the first time and getting `ClassNotFoundException`.

When downloading the project, I accepted all default options (Enter) when prompted. Thanks for considering this suggestion for the Quickstart docs.

**Comment by bwoskow-ld** [comment]
Thanks for letting us know. We'll fix the in-app quickstart so that this isn't a problem.

In the meantime, I'm going to close this issue as the fix is in a different (private) repository. This repository is only used as a standalone example for using the Java SDK.
