### ISSUE TITLE
SDK Version in POM 4.8

### ISSUE THREAD

**Issue by whosthegoss** [launchdarkly/hello-java#5]
Online documentation for working with the Launchdarkly SDK shows examples with 4.12.0. 

Java SDK dependency version for this project is 4.8.0. A lot of the code examples simply would not compile with 4.8.0. It wasn't until someone else was working with me that they pointed out the dependency version being 4 versions behind the documentation.

**Comment by eli-darkly** [comment]
Yikes, sorry - this should be a version range `[4.0,5.0)`, as it is in the [reference guide](https://docs.launchdarkly.com/sdk/server-side/java#getting-started). I'll fix that right away, thanks for pointing it out.

**Comment by eli-darkly** [comment]
Er, I spoke too soon - it already does use a version range, but that does not have the desired effect of using the _highest_ compatible version. Well, we'll fix it in any case.

**Comment by whosthegoss** [comment]
Thanks!

**Comment by eli-darkly** [comment]
Well, for right now I can just hard-code the latest version, but it's going to be hard to make it auto-update as long as it's using Maven. We've considered migrating this project to use Gradle instead; Gradle seems to be at least as popular as Maven is these days, it has a more flexible dependency versioning model, and it wouldn't make any difference to the actual Java code of the demo. Unless and until we do that, I'll go back to updating this version (and the documentation) with each release.

**Comment by whosthegoss** [comment]
Might I suggest as part of the README that attention be paid to the version and if it matches the online spec as a backup for when this may fall behind? Didn't mean to make a ton of extra work. Appreciate all the responses.

**Comment by eli-darkly** [comment]
Yes, good point about the readme. I've updated that as well as the hard-coded version, and we'll be making a similar change in the online docs.

**Comment by eli-darkly** [comment]
We've updated this demo so that it now uses Gradle and automatically gets the current SDK release.
